### ISSUE TITLE
udid is null

### ISSUE THREAD

**Issue by orionJag** [jimbobbennett/AzureMapsGeofenceDemo#2]
Jim

        Trying out your demo for the Geofence and it's gives error on the following line

            geofence_udid = response.json()['udid'] 

        it errors with  " KeyError: 'udid'", despite the fact it's a successful post - any thoughts on what am I missing ? 

 ![GeoFence_Post](https://user-images.githubusercontent.com/50410385/85786804-9b304d00-b6f8-11ea-9919-5a2714011d40.png)
          
      Thanks

**Comment by jimbobbennett** [comment]
I wonder if they changed the API. Whats the full value of `response.json()`?

**Comment by orionJag** [comment]
response_json:  {'resourceLocation': 'https://atlas.micros...ersion=1.0', 'status': 'Succeeded'} Thanks From: Jim BennettSent: Thursday, June 25, 2020 4:58 PMTo: jimbobbennett/AzureMapsGeofenceDemoCc: orionJag; AuthorSubject: Re: [jimbobbennett/AzureMapsGeofenceDemo] udid is null (#2) I wonder if they changed the API. Whats the full value of response.json()?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jimbobbennett** [comment]
Yup - the API has changed. Check the latest code, should have a fix.

**Comment by orionJag** [comment]
Jim
         Thanks for the quick response, it works perfect now.  Appreciate all your support.
